### PR TITLE
Decompile more stuff

### PR DESCRIPTION
**Pull request by orphanlol**
DevHaxx soon, Intervoid had a fetch part removed because I couldn't understand how that part worked so I removed it.

### CODE REVIEW

**Review by orphanlol — COMMENTED** [review]
this is stupid

**Comment by SnesFX** [comment]
good work king 🙏

**Comment by orphanlol** [comment]
add me on disacoered

**Comment by SnesFX** [comment]
is your disc the same as your github user?

**Comment by orphanlol** [comment]
yes lolz

**Comment by SnesFX** [comment]
sent a request

**Pull request merged**
